pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out code...'
                git url: 'https://github.com/ayamaber88/Testing-E-Commerce.git',
                   
                    branch: 'main',
                    changelog: false,
                    poll: false
            }
        }
        stage('Build') {
            steps {
                echo 'Building the Maven project...'
                sh 'cd Automation/Demoplaze_Fullproject-master'
                sh 'mvn clean install -DskipTests'
            }
        }
        stage('Test') {
            steps {
                echo 'Running the TestNG tests...'
                sh 'cd Automation/Demoplaze_Fullproject-master'
                sh 'mvn test'
                junit 'Automation/Demoplaze_Fullproject-master/target/surefire-reports/TEST-*.xml'
            }
        }
        // You can add more stages here for reporting, etc.
    }
}
