pipeline {
    agent any
    stages {
        stage('Test Shell') {
            steps {
                sh '"C:\\Program Files\\Git\\bin\\sh.exe" -c "echo Hello from Shell"'
            }
        }
        // ... other stages
    }
}
