stage('Run API Tests with Newman') {
    steps {
        echo 'Running API Tests with Newman...'
        withEnv(["PATH+NODE=${env.NODE_HOME}"]) {
            executable "${env.NEWMAN_HOME}\\newman.cmd"
            args "run", "Demoblaze API Tests.postman_collection.json"
        }
    }
}
