pipeline {
    agent any

   

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/ayamaher88/Testing-E-Commerce-.git'
                checkout scm
            }
        }

        stage('Run API Tests with Newman') {
            steps {
                echo 'Running API Tests with Newman...'
                bat 'newman run "Demoblaze API Tests.postman_collection.json"'
            }
        }

        stage('Publish API Test Results (Optional)') {
            steps {
                echo 'Publishing API Test Results (if any)...'
                // ... (reporting configuration as needed)
            }
        }

        stage('Post-Build Actions') {
            steps {
                script {
        echo 'Performing post-build actions...'
        // Add your actual post-build steps here
      
            }
        }
    }
}
}
